spring.config.import=optional:file:.env[.properties]

spring.application.name=${SPRING_APPLICATION_NAME:flowra-backend}

server.port=${PORT:8080}

spring.datasource.url=mysql://root:wlpVinwcSfccfMzHAnWCapZwosuBcffQ@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=wlpVinwcSfccfMzHAnWCapZwosuBcffQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
spring.jpa.open-in-view=true

spring.jackson.serialization.indent-output=true
spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:10MB}

logging.level.org.springframework.web=${LOG_LEVEL_SPRING:INFO}
logging.level.org.hibernate.SQL=${LOG_LEVEL_HIBERNATE:DEBUG}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
razorpay.currency=${RAZORPAY_CURRENCY:INR}
razorpay.company.name=${RAZORPAY_COMPANY_NAME:FLOWRA Artisanal Florist}